# Generated by Django 6.0.3 on 2026-04-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
