# Generated by Django 6.0.3 on 2026-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
