# Generated by Django 6.0.3 on 2026-04-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meeting_is_all_day_meeting_is_scheduled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='meetings.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'email')},
            },
        ),
    ]
