# Generated by Django 6.0.3 on 2026-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_directchat_directchatmessage_directchatparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recording_thumbs/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
