# Generated by Django 6.0.3 on 2026-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meetingtranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='require_admission',
            field=models.BooleanField(default=False),
        ),
    ]
