# Generated by Django 6.0.3 on 2026-04-25 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_waitingroomknock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='UserChatRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'chat'], name='meetings_us_user_id_823b0f_idx')],
                'unique_together': {('user', 'chat')},
            },
        ),
    ]
