# Generated by Django 6.0.3 on 2026-04-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_directchatmessage_is_read_userchatread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('max_duration_minutes', models.PositiveIntegerField(default=40, help_text='Maximum meeting duration in minutes. 0 = unlimited.')),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum simultaneous participants per meeting.')),
                ('can_record', models.BooleanField(default=False)),
                ('can_use_waiting_room', models.BooleanField(default=False)),
                ('can_schedule', models.BooleanField(default=False)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD (for display).', max_digits=8)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When the host first activated (started) the meeting.', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(default=40, help_text='Max meeting duration in minutes. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text="Max simultaneous participants (copied from host's plan at creation)."),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires (lifetime or free).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='meetings.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
