# Generated by Django 6.0.3 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_meetingcapacityqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='only_host_audio',
            field=models.BooleanField(default=False, help_text='Only host can speak; participant mics are disabled.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='only_host_chat',
            field=models.BooleanField(default=False, help_text='Participants cannot send chat messages (read-only).'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='only_host_screenshare',
            field=models.BooleanField(default=False, help_text='Participants cannot share their screen.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='only_host_video',
            field=models.BooleanField(default=False, help_text='Participants cannot turn on their cameras.'),
        ),
    ]
